FROM alpine:latest

# install php fpm and include wordpress volume
RUN apk add php8 php8-fpm php8-opcache
RUN apk add php8-gd php8-zlib php8-curl
RUN apk add tzdata
RUN apk add bash
RUN adduser -D -g 'Nginx www user' -h /home/www/ www

COPY --chown=www:www ./tools/setup.sh /setup.sh

# RUN ln -s /usr/bin/php8 /usr/bin/php

# Installing composer
# RUN apk add curl
# RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
# RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
# RUN rm -rf composer-setup.php

# Configure PHP
RUN mkdir -p /run/php/
RUN touch /run/php/php8.0-fpm.pid

# Building process
# RUN composer install --no-dev

RUN sh setup.sh

# install wordpress

RUN wget http://wordpress.org/latest.tar.gz 
RUN tar -xf latest.tar.gz -C /home/www

CMD [ "/bin/bash", "-c", "php-fpm8 -F" ]