USE mysql;
FLUSH PRIVILEGES ;

SET PASSWORD FOR 'root'@'localhost' = PASSWORD('rootpass');

CREATE DATABASE IF NOT EXISTS wp CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER IF NOT EXISTS 'owner'@'%' IDENTIFIED BY 'ownerpass';
CREATE USER IF NOT EXISTS 'dev'@'%' IDENTIFIED BY 'devpass';

GRANT ALL PRIVILEGES ON wp.* TO 'owner'@'%' IDENTIFIED BY 'ownerpass' WITH GRANT OPTION; 
GRANT ALL PRIVILEGES ON wp.* TO 'dev'@'%' IDENTIFIED BY 'devpass' WITH GRANT OPTION;

FLUSH PRIVILEGES ;